### PR TITLE
Fix #11, #13 and #20 and add Python3 support tp apriori script.

### LINKED ISSUE #11: Many issues
No python3 optimization: `print value` should be `print(value)`... and you try to use indexing in dictionaries which will give errors.

### PR DESCRIPTION
**Pull request by muety**

### CODE REVIEW

**Comment by muety** [comment]
@asaini Could you please merge this? :)

**Comment by asaini** [comment]
@n1try : Can you resubmit the PR on the python3 branch?

**Comment by muety** [comment]
Done.
#27

**Comment by asaini** [comment]
Closing. Fixed in #27

**Pull request closed without merging**
